

# This file was *autogenerated* from the file solve_linear_sat.sage
from sage.all_cmdline import *   # import sage library

_sage_const_78 = Integer(78); _sage_const_8 = Integer(8); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0xF = Integer(0xF); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20)# Reads the original GF(16) equations:
#     F(c)*x_k_j + ... == F(r)
#
# Builds the system as Sage polynomials over GF(16), then bit-blasts the
# complete GF(16) polynomial system to a BooleanPolynomialRing over GF(2),
# in the same style as gf2m_system_to_gf2() from the second code.
#
# The resulting Boolean ANF equations are sent to CryptoMiniSat.
#
# Supports Boolean equations of arbitrary monomial degree by introducing
# Tseitin AND variables for nonlinear monomials.

from sage.all import *
from sage.sat.solvers.cryptominisat import CryptoMiniSat
from solve_pycrypto import solve_with_pycryptosat, check_known_assignment

from collections import Counter
import pycryptosat
import re
import sys
import time

# ============================================================
# PARAMETERS
# ============================================================

v = _sage_const_78 
o = _sage_const_8 

NUM_GF16_VARS = v * o
INPUT_FILE = "mayo_equations_linear.txt"
BOOLEAN_EQ_FILE = "boolean_anf_equations.txt"

# GF(16) = GF(2)[a] / (a^4 + a + 1)
PR = PolynomialRing(GF(_sage_const_2 ), names=('z',)); (z,) = PR._first_ngens(1)
F = GF(_sage_const_2 **_sage_const_4 , modulus=z**_sage_const_4  + z + _sage_const_1 , names=('a',)); (a,) = F._first_ngens(1)

# One GF(16) variable for every O[k][j].
# Variable ordering:
#   x_0_0, x_0_1, ..., x_77_7
gf_names = ["x_%d_%d" % (k, j) for k in range(v) for j in range(o)]
R = PolynomialRing(F, names=gf_names)
Rvars = R.gens()

gf_var_map = {}
for k in range(v):
    for j in range(o):
        gf_var_map[(k, j)] = Rvars[k * o + j]

print("Input file          :", INPUT_FILE)
print("GF(16) variables    :", NUM_GF16_VARS)
print("GF(16) field        :", F)
print("Modulus             :", F.modulus())


# ============================================================
# GF(16) INTEGER/NIBBLE CONVERSION
#
# Integer c in F(c) is interpreted in polynomial-basis bits:
#
#   c = b0 + 2*b1 + 4*b2 + 8*b3
#     -> b0 + b1*a + b2*a^2 + b3*a^3
# ============================================================

def int_to_gf16(c):
    c = int(c) & _sage_const_0xF 
    value = F(_sage_const_0 )
    for bit in range(_sage_const_4 ):
        if (c >> bit) & _sage_const_1 :
            value += a**bit
    return value


def gf16_to_int(c):
    c = F(c)
    poly = c.polynomial()
    value = _sage_const_0 
    for bit in range(_sage_const_4 ):
        if bit <= poly.degree() and int(poly[bit]) & _sage_const_1 :
            value |= (_sage_const_1  << bit)
    return value & _sage_const_0xF 


# Sanity-check the nibble mapping.
for c in range(_sage_const_16 ):
    if gf16_to_int(int_to_gf16(c)) != c:
        raise RuntimeError("GF(16) nibble conversion failed for %d" % c)

print("PASS: GF(16) nibble mapping sanity check")


# ============================================================
# PARSE ORIGINAL TEXT EQUATIONS INTO SAGE GF(16) POLYNOMIALS
# ============================================================

VARIABLE_TERM_RE = re.compile(
    r'^F\(\s*(\d+)\s*\)\s*\*\s*x_(\d+)_(\d+)$'
)

CONSTANT_TERM_RE = re.compile(
    r'^F\(\s*(\d+)\s*\)$'
)

BARE_CONSTANT_RE = re.compile(
    r'^(\d+)$'
)


def parse_side_to_polynomial(side):
    """
    Convert one textual side into a polynomial in R over GF(16).
    """
    side = side.strip()

    if side == "":
        return R(_sage_const_0 )

    result = R(_sage_const_0 )

    for raw_term in side.split("+"):
        term = raw_term.strip()

        if not term:
            continue

        m = VARIABLE_TERM_RE.match(term)
        if m:
            coeff = int_to_gf16(int(m.group(_sage_const_1 )))
            k = int(m.group(_sage_const_2 ))
            j = int(m.group(_sage_const_3 ))

            if not (_sage_const_0  <= k < v):
                raise ValueError("Invalid row index k=%d" % k)

            if not (_sage_const_0  <= j < o):
                raise ValueError("Invalid column index j=%d" % j)

            result += R(coeff) * gf_var_map[(k, j)]
            continue

        m = CONSTANT_TERM_RE.match(term)
        if m:
            result += R(int_to_gf16(int(m.group(_sage_const_1 ))))
            continue

        m = BARE_CONSTANT_RE.match(term)
        if m:
            result += R(int_to_gf16(int(m.group(_sage_const_1 ))))
            continue

        raise ValueError("Could not parse term: %s" % term)

    return result


def parse_equation_to_polynomial(line):
    """
    Parse:
        lhs == rhs

    and return the GF(16) polynomial:
        lhs + rhs

    because subtraction equals addition in characteristic 2.
    The equation represented is therefore:
        lhs + rhs = 0
    """
    if "==" not in line:
        raise ValueError("Equation does not contain ==:\n%s" % line)

    lhs_text, rhs_text = line.split("==", _sage_const_1 )

    lhs = parse_side_to_polynomial(lhs_text)
    rhs = parse_side_to_polynomial(rhs_text)

    return lhs + rhs


gf16_system = []

with open(INPUT_FILE, "r") as fp:
    for line_no, line in enumerate(fp, start=_sage_const_1 ):
        line = line.strip()

        if not line or line.startswith("#"):
            continue

        try:
            f = parse_equation_to_polynomial(line)
        except Exception as e:
            print("\nERROR parsing line", line_no)
            print(line)
            print("Reason:", e)
            raise

        gf16_system.append(f)

print("\nParsed GF(16) polynomial equations:", len(gf16_system))

if not gf16_system:
    raise RuntimeError("No equations were parsed")

degrees = [f.total_degree() for f in gf16_system]
print("Maximum GF(16) polynomial degree  :", max(degrees))
print("All GF(16) equations linear       :", max(degrees) <= _sage_const_1 )


# ============================================================
# GF(2^4) POLYNOMIAL SYSTEM -> BOOLEAN POLYNOMIAL SYSTEM
#
# This is the same general conversion style as the SECOND code:
#
#   each GF(16) variable x becomes four Boolean variables
#
#       x_0, x_1, x_2, x_3
#
#   representing
#
#       x = x_0 + x_1*a + x_2*a^2 + x_3*a^3.
#
# GF(16) multiplication is expanded as polynomial multiplication
# over GF(2), followed by reduction modulo a^4 + a + 1.
#
# Unlike the old first code, this does NOT use precomputed
# multiplication matrices. It bit-blasts the Sage GF(16)
# polynomial system directly.
# ============================================================

def gf2m_system_to_gf2(system):
    """
    Convert a polynomial system over GF(2^m) into a Boolean
    polynomial system over GF(2).

    For GF(16), each field variable:

        x

    is represented as:

        x = x_b0
          + x_b1*a
          + x_b2*a^2
          + x_b3*a^3

    using the polynomial basis defined by:

        a^4 + a + 1 = 0

    Each GF(16) equation produces exactly 4 Boolean equations.
    """

    if not system:
        raise ValueError(
            "GF(16) system is empty"
        )

    # ========================================================
    # Original polynomial ring over GF(16)
    # ========================================================

    R_ext = system[_sage_const_0 ].parent()

    F_ext = R_ext.base_ring()

    m = F_ext.degree()

    vars_ext = list(
        R_ext.gens()
    )

    n = len(vars_ext)

    print("\n========================================")
    print("GF(16) -> GF(2) CONVERSION")
    print("========================================")

    print(
        "Extension degree m :",
        m
    )

    print(
        "GF(16) variables   :",
        n
    )

    print(
        "GF(16) equations   :",
        len(system)
    )

    # ========================================================
    # Modulus
    #
    # For MAYO:
    #
    #     a^4 + a + 1
    #
    # ========================================================

    modulus = F_ext.modulus()

    modulus_coeffs = list(
        modulus.list()
    )

    print(
        "GF(16) modulus     :",
        modulus
    )

    # ========================================================
    # Boolean ring
    #
    # Each GF(16) variable gets m Boolean variables.
    # ========================================================

    bool_names = []

    for var in vars_ext:

        for bit in range(m):

            bool_names.append(
                "%s_b%d"
                %
                (
                    str(var),
                    bit
                )
            )

    B = BooleanPolynomialRing(
        n * m,
        names=bool_names
    )

    Bvars = list(
        B.gens()
    )

    # ========================================================
    # Map:
    #
    # GF(16):
    #
    #     x_0_0
    #
    # ->
    #
    # GF(2):
    #
    #     [
    #       x_0_0_b0,
    #       x_0_0_b1,
    #       x_0_0_b2,
    #       x_0_0_b3
    #     ]
    #
    # ========================================================

    var_bits = {}

    index = _sage_const_0 

    for var in vars_ext:

        var_bits[var] = list(
            Bvars[
                index:
                index + m
            ]
        )

        index += m

    # ========================================================
    # Convert GF(16) element -> bit vector
    #
    # Example:
    #
    #     a^3 + a + 1
    #
    # ->
    #
    #     [1,1,0,1]
    #
    # ========================================================

    def field_element_to_bits(c):

        c = F_ext(c)

        poly = c.polynomial()

        coeffs = list(
            poly.list()
        )

        coeffs += [
            _sage_const_0 
        ] * (
            m - len(coeffs)
        )

        return [

            B(
                int(coeffs[i])
            )

            for i in range(m)

        ]

    # ========================================================
    # GF(16) symbolic multiplication
    #
    # Inputs:
    #
    #     u = [u0,u1,u2,u3]
    #     v = [v0,v1,v2,v3]
    #
    # representing:
    #
    #     u0 + u1*a + ...
    #
    # Multiply polynomially, then reduce modulo:
    #
    #     a^4 + a + 1
    #
    # ========================================================

    def field_mult(u_bits, v_bits):

        tmp = [

            B(_sage_const_0 )

            for _ in range(
                _sage_const_2  * m - _sage_const_1 
            )

        ]

        # ----------------------------------------------------
        # Polynomial multiplication
        # ----------------------------------------------------

        for i in range(m):

            for j in range(m):

                tmp[i + j] += (
                    u_bits[i]
                    *
                    v_bits[j]
                )

        # ----------------------------------------------------
        # Modular reduction
        #
        # modulus:
        #
        #     a^m + p_(m-1)a^(m-1) + ... + p0
        #
        # Since characteristic = 2:
        #
        #     a^m =
        #       p_(m-1)a^(m-1) + ... + p0
        #
        # ----------------------------------------------------

        for degree in range(
            _sage_const_2  * m - _sage_const_2 ,
            m - _sage_const_1 ,
            -_sage_const_1 
        ):

            high = tmp[
                degree
            ]

            if high == B(_sage_const_0 ):

                continue

            for i in range(m):

                if (
                    int(
                        modulus_coeffs[i]
                    )
                    & _sage_const_1 
                ):

                    tmp[
                        degree - m + i
                    ] += high

            tmp[
                degree
            ] = B(_sage_const_0 )

        return tmp[:m]

    # ========================================================
    # Multiply bit vector by GF variable^exponent
    # ========================================================

    def multiply_by_variable_power(
        term_bits,
        variable,
        exponent
    ):

        result = list(
            term_bits
        )

        bits = var_bits[
            variable
        ]

        for _ in range(
            exponent
        ):

            result = field_mult(
                result,
                bits
            )

        return result

    # ========================================================
    # MAIN CONVERSION
    # ========================================================

    boolean_eqs = []

    print(
        "\nConverting equations..."
    )

    for eq_index, f in enumerate(
        system
    ):

        # Resulting GF(16) value:
        #
        #     result[0]
        #       + result[1]*a
        #       + result[2]*a^2
        #       + result[3]*a^3

        result = [

            B(_sage_const_0 )

            for _ in range(m)

        ]

        # ====================================================
        # IMPORTANT FIX
        #
        # Explicitly iterate over Sage monomials instead of
        # relying on f.dict().
        # ====================================================

        monomials = f.monomials()

        for mon in monomials:

            # ------------------------------------------------
            # Get coefficient of this monomial
            # ------------------------------------------------

            coeff = F_ext(
                f.monomial_coefficient(
                    mon
                )
            )

            # Start term with coefficient bits
            term_bits = field_element_to_bits(
                coeff
            )

            # ------------------------------------------------
            # Extract exponent tuple
            #
            # Example:
            #
            #     x0*x3^2
            #
            # ->
            #
            #     (1,0,0,2,...)
            #
            # ------------------------------------------------

            exponent_tuple = tuple(
                mon.exponents()[_sage_const_0 ]
            )

            if len(
                exponent_tuple
            ) != n:

                raise RuntimeError(
                    "Exponent tuple length mismatch: "
                    "%d != %d"
                    %
                    (
                        len(
                            exponent_tuple
                        ),
                        n
                    )
                )

            # ------------------------------------------------
            # Multiply coefficient by every variable power
            # ------------------------------------------------

            for var_index, exponent in enumerate(
                exponent_tuple
            ):

                exponent = int(
                    exponent
                )

                if exponent == _sage_const_0 :

                    continue

                variable = vars_ext[
                    var_index
                ]

                term_bits = (
                    multiply_by_variable_power(
                        term_bits,
                        variable,
                        exponent
                    )
                )

            # ------------------------------------------------
            # Add term into equation
            #
            # GF(16) addition = component-wise XOR
            # ------------------------------------------------

            for bit in range(m):

                result[
                    bit
                ] += term_bits[
                    bit
                ]

        # ----------------------------------------------------
        # Each GF(16) equation gives m Boolean equations.
        # ----------------------------------------------------

        for bit in range(m):

            boolean_eqs.append(
                B(
                    result[
                        bit
                    ]
                )
            )

        

    # ========================================================
    # FINAL SANITY CHECK
    # ========================================================

    print("\n========================================")
    print("GF(16) -> GF(2) CONVERSION SUMMARY")
    print("========================================")

    print(
        "GF(16) equations :",
        len(system)
    )

    print(
        "Expected Boolean :",
        len(system) * m
    )

    print(
        "Actual Boolean   :",
        len(boolean_eqs)
    )

    nonzero = sum(

        _sage_const_1 

        for f in boolean_eqs

        if f != B(_sage_const_0 )

    )

    print(
        "Nonzero Boolean  :",
        nonzero
    )

    print(
        "Zero Boolean     :",
        len(boolean_eqs)
        -
        nonzero
    )

    if len(boolean_eqs) != (
        len(system) * m
    ):

        raise RuntimeError(
            "Incorrect number of Boolean equations"
        )

    if nonzero == _sage_const_0 :

        raise RuntimeError(
            "ALL Boolean equations became zero. "
            "GF(16) -> GF(2) conversion failed."
        )

    return (
        B,
        var_bits,
        boolean_eqs
    )


print("\n========================================")
print("CHECKING ORIGINAL GF(16) SYSTEM")
print("========================================")

for i in range(min(_sage_const_3 , len(gf16_system))):

    f = gf16_system[i]

    print("\nEquation", i)

    print(
        "Polynomial:",
        f
    )

    print(
        "Is zero:",
        f == _sage_const_0 
    )

    print(
        "Degree:",
        f.total_degree()
    )

    print(
        "Number monomials:",
        len(
            f.monomials()
        )
    )

    print(
        "First monomials:",
        f.monomials()[:_sage_const_5 ]
    )

    print(
        "First coefficients:",
        f.coefficients()[:_sage_const_5 ]
    )


print("\n========================================")
print("BIT-BLASTING GF(16) -> GF(2)")
print("========================================")

t0 = time.time()

B, var_bits, boolean_eqs = gf2m_system_to_gf2(gf16_system)

print("Boolean variables       :", B.ngens())
print("Boolean equations       :", len(boolean_eqs))
print("Expected equations      :", _sage_const_4  * len(gf16_system))
print("Bit-blast time          : %.3f s" % (time.time() - t0))

bool_degrees = [f.degree() for f in boolean_eqs if f != _sage_const_0 ]
max_bool_degree = max(bool_degrees) if bool_degrees else _sage_const_0 

print("Maximum Boolean degree  :", max_bool_degree)
print("Boolean system linear   :", max_bool_degree <= _sage_const_1 )


# ============================================================
# WRITE BOOLEAN ANF EQUATIONS
# ============================================================

with open(BOOLEAN_EQ_FILE, "w") as fp:
    fp.write("# Boolean ANF equations generated from GF(16)\n")
    fp.write("# Each line is polynomial = 0 over GF(2)\n")
    fp.write("# Boolean variables: %d\n" % B.ngens())
    fp.write("# Boolean equations: %d\n\n" % len(boolean_eqs))

    for i, f in enumerate(boolean_eqs, start=_sage_const_1 ):
        fp.write("Eq %5d: %s = 0\n" % (i, f))

print("Written Boolean ANF system:", BOOLEAN_EQ_FILE)


# ============================================================
# BOOLEAN ANF -> CRYPTOMINISAT
#
# Each Boolean polynomial:
#
#   m1 + m2 + ... + c = 0
#
# becomes an XOR constraint:
#
#   m1 XOR m2 XOR ... = c
#
# For nonlinear monomials, introduce a fresh SAT variable z and
# encode:
#
#   z <-> AND(x1, x2, ..., xd)
#
# using CNF:
#
#   (~z OR xi)              for every xi
#   (z OR ~x1 OR ... OR ~xd)
#
# Then z is used in the XOR clause.
# ============================================================


from sage.sat.solvers.satsolver import SAT

def solve_with_sage_sat(boolean_eqs):
    # Pass "cryptominisat" or "picosat" or "glucose"
    solver = SAT("cryptominisat")  
    
    # Solve the Boolean Polynomial System directly
    solution = solver(boolean_eqs)
    
    if solution is False or solution is None:
        return None
    
    # solution is a tuple/dict of variable assignments
    # Convert to dict if needed
    if isinstance(solution, dict):
        return solution
    elif isinstance(solution, (tuple, list)):
        # If it's a tuple/list, try to map to variables
        B = boolean_eqs[_sage_const_0 ].parent()
        vars_B = list(B.gens())
        result = {}
        for i, var in enumerate(vars_B):
            if i < len(solution):
                result[var] = bool(solution[i])
        return result
    else:
        return solution

"""
def solve_with_pycryptosat(boolean_eqs):
    if not boolean_eqs:
        return {}

    B = boolean_eqs[0].parent()
    vars_B = list(B.gens())

    # pycryptosat uses 0-based indexing for variables
    var_map = {v: i for i, v in enumerate(vars_B)}
    next_var = len(vars_B)

    solver = pycryptosat.Solver()
    product_map = {}

    def get_product_var(x, y):
        nonlocal next_var
        key = tuple(sorted((x, y), key=str))
        if key in product_map:
            return product_map[key]

        z = next_var
        next_var += 1
        product_map[key] = z

        # z = x AND y encoded into CNF clauses
        # (¬z ∨ x) ∧ (¬z ∨ y) ∧ (¬x ∨ ¬y ∨ z)
        # Note: 1-based literals in pycryptosat clauses (+N for pos, -N for neg)
        vx = var_map[x] + 1
        vy = var_map[y] + 1
        vz = z + 1

        solver.add_clause([-vz, vx])
        solver.add_clause([-vz, vy])
        solver.add_clause([-vx, -vy, vz])

        return z

    for f in boolean_eqs:
        raw_xor_vars = []
        const_term = 0

        for mon in f.monomials():
            vars_in_mon = mon.variables()

            if len(vars_in_mon) == 0:
                const_term ^= 1
            elif len(vars_in_mon) == 1:
                raw_xor_vars.append(var_map[vars_in_mon[0]])
            elif len(vars_in_mon) == 2:
                z = get_product_var(vars_in_mon[0], vars_in_mon[1])
                raw_xor_vars.append(z)
            else:
                raise NotImplementedError("Only degree <= 2 supported")

        # Simplify duplicate XOR terms (x ^ x = 0)
        counts = Counter(raw_xor_vars)
        simplified_vars = [var_id for var_id, count in counts.items() if count % 2 == 1]

        if not simplified_vars:
            if const_term == 1:
                # Contradiction 0 = 1
                solver.add_clause([1])
                solver.add_clause([-1])
            continue

        # pycryptosat add_xor_clause takes 1-based variable IDs and boolean RHS
        # Convert to tuple of explicit integers
        xor_vars_1based = tuple(int(v+1) for v in simplified_vars)
        # print(type(xor_vars_1based[0]))
        solver.add_xor_clause(xor_vars_1based, bool(const_term))

    sat, solution = solver.solve()

    if not sat:
        return None

    # solution is a tuple of booleans/None starting at index 1
    # Index 0 is dummy/padding in pycryptosat output tuple
    result = {v: bool(solution[var_map[v] + 1]) for v in vars_B}
    return result
"""
"""
def solve_with_cryptominisat(boolean_eqs):
    if not boolean_eqs:
        return {}

    B = boolean_eqs[0].parent()
    vars_B = list(B.gens())

    solver = CryptoMiniSat()
    
    # Map Boolean variables -> 1-based CMS variable IDs
    var_map = {v: i + 1 for i, v in enumerate(vars_B)}
    next_var = len(vars_B) + 1

    product_map = {}

    def get_product_var(x, y):
        nonlocal next_var

        # Sort variables to ensure unique keys for commutative multiplication
        key = tuple(sorted((x, y), key=str))
        if key in product_map:
            return product_map[key]

        z = next_var
        next_var += 1
        product_map[key] = z

        # Direct CNF clauses for z = x AND y
        # (¬z ∨ x) ∧ (¬z ∨ y) ∧ (¬x ∨ ¬y ∨ z)
        solver.add_clause([-z, var_map[x]])
        solver.add_clause([-z, var_map[y]])
        solver.add_clause([-var_map[x], -var_map[y], z])

        return z

    for f in boolean_eqs:
        raw_xor_vars = []
        const_term = 0

        for mon in f.monomials():
            vars_in_mon = mon.variables()

            if len(vars_in_mon) == 0:
                const_term ^= 1
            elif len(vars_in_mon) == 1:
                raw_xor_vars.append(var_map[vars_in_mon[0]])
            elif len(vars_in_mon) == 2:
                z = get_product_var(vars_in_mon[0], vars_in_mon[1])
                raw_xor_vars.append(z)
            else:
                raise NotImplementedError("Only degree <= 2 supported")

        # FIX BUG 2: Reduce duplicate variables in XOR clauses (x ^ x = 0)
        counts = Counter(raw_xor_vars)
        simplified_xor_vars = [var_id for var_id, count in counts.items() if count % 2 == 1]

        # Handle simplified XOR edge cases
        if not simplified_xor_vars:
            if const_term == 1:
                # 0 = 1 (Unsatisfiable equation like x ^ x = 1)
                solver.add_clause([1])
                solver.add_clause([-1])
            continue

        # Add the cleaned XOR clause
        solver.add_xor_clause(tuple(simplified_xor_vars), rhs=bool(const_term))

    sat = solver()

    if not sat:
        return None
    
    # Extract original variable values from the solver
    result = {}
    for v in vars_B:
        idx = var_map[v]
        # Get the variable value from the solver (1-based indexing)
        val = solver.var_value(idx)
        result[v] = bool(val) if val is not None else False

    return result
    """
used_original_vars = set()

for f in boolean_eqs:
    for mon in f.monomials():
        for var in mon.variables():
            used_original_vars.add(var)

print("\n========================================")
print("BOOLEAN VARIABLE USAGE")
print("========================================")
print("Variables in Boolean ring :", B.ngens())
print("Variables actually used   :", len(used_original_vars))
print("Unused/free variables     :", B.ngens() - len(used_original_vars))

unused = [
    v for v in B.gens()
    if v not in used_original_vars
]

if unused:
    print("\nFirst unused variables:")
    for x in unused[:_sage_const_20 ]:
        print(" ", x)

print("\n========================================")
print("RUNNING CRYPTOMINISAT")
print("========================================")

solve_start = time.time()
assignment = solve_with_pycryptosat(boolean_eqs)
print("Assignment size:", len(assignment) if assignment else _sage_const_0 )
print("True count:", sum(_sage_const_1  for v in assignment.values() if v) if assignment else _sage_const_0 )

# Sanity-check: does this assignment actually satisfy the boolean system?
bad = _sage_const_0 
for i, f in enumerate(boolean_eqs):
    val = f.subs({v: assignment.get(v, False) for v in f.variables()})
    if val != _sage_const_0 :
        bad += _sage_const_1 
        if bad <= _sage_const_3 :
            print("Boolean eq", i+_sage_const_1 , "violated:", f)
print("Violated boolean equations:", bad, "/", len(boolean_eqs))
solve_time = time.time() - solve_start

if assignment is None:
    print("\n========================================")
    print("RESULT: UNSAT")
    print("========================================")
    sys.exit(_sage_const_1 )

print("\nRESULT: SAT")
print("CryptoMiniSat solve time: %.3f s" % solve_time)

# ============================================================
# RECOVER GF(16) O MATRIX FROM BOOLEAN ASSIGNMENT
# ============================================================

O_sat_int = [
    [_sage_const_0  for _ in range(o)]
    for _ in range(v)
]

O_sat_F = Matrix(F, v, o)

for k in range(v):
    for j in range(o):
        gf_var = gf_var_map[(k, j)]
        bits = var_bits[gf_var]

        nibble = _sage_const_0 

        for bit in range(_sage_const_4 ):
            # Handle missing keys in assignment (treat as False)
            bit_value = assignment.get(bits[bit], False) if isinstance(assignment, dict) else False
            nibble |= (bit_value << bit)

        nibble &= _sage_const_0xF 

        O_sat_int[k][j] = nibble
        O_sat_F[k, j] = int_to_gf16(nibble)


print("\n========================================")
print("CRYPTOMINISAT RECOVERED O")
print("========================================")

for k in range(v):
    print(
        "O[%2d] =" % k,
        " ".join(
            "%x" % O_sat_int[k][j]
            for j in range(o)
        )
    )


# ============================================================
# VERIFY AGAINST ORIGINAL GF(16) POLYNOMIAL SYSTEM
# ============================================================

print("\n========================================")
print("VERIFYING AGAINST ORIGINAL GF(16) SYSTEM")
print("========================================")

gf_subs = {}

for k in range(v):
    for j in range(o):
        gf_subs[gf_var_map[(k, j)]] = O_sat_F[k, j]

verification_ok = True

for eq_index, f in enumerate(gf16_system):
    value = F(f.subs(gf_subs))

    if value != _sage_const_0 :
        print("FAIL at GF(16) equation", eq_index + _sage_const_1 )
        print("Residual:", value)
        verification_ok = False
        break

if verification_ok:
    print(
        "PASS: all %d original GF(16) equations satisfied"
        % len(gf16_system)
    )
else:
    print("FAIL: CryptoMiniSat model does not satisfy GF(16) equations")
    sys.exit(_sage_const_1 )


# ============================================================
# OPTIONAL: VERIFY EVERY BOOLEAN EQUATION DIRECTLY
# ============================================================

print("\n========================================")
print("VERIFYING BOOLEAN ANF MODEL")
print("========================================")

boolean_ok = True

for eq_index, f in enumerate(boolean_eqs):
    # Create a full assignment dict, treating missing keys as False
    full_assignment = {}
    if isinstance(assignment, dict):
        for var in f.variables():
            full_assignment[var] = assignment.get(var, False)
    
    value = f.subs(full_assignment) if full_assignment else _sage_const_0 

    if value != _sage_const_0 :
        print("FAIL at Boolean equation", eq_index + _sage_const_1 )
        print("Residual:", value)
        boolean_ok = False
        break

if boolean_ok:
    print(
        "PASS: all %d Boolean equations satisfied"
        % len(boolean_eqs)
    )
else:
    print("FAIL: Boolean model verification failed")
    sys.exit(_sage_const_1 )


print("\n========================================")
print("FINAL SUMMARY")
print("========================================")
print("Original GF(16) equations :", len(gf16_system))
print("GF(16) variables          :", NUM_GF16_VARS)
print("Boolean variables         :", B.ngens())
print("Boolean equations         :", len(boolean_eqs))
print("Maximum Boolean degree    :", max_bool_degree)
print("CryptoMiniSat             : SAT")
print("GF(16) verification       :", verification_ok)
print("Boolean verification      :", boolean_ok)
print("========================================")

