

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_78 = Integer(78); _sage_const_8 = Integer(8)# -------------------------------------------------------
# Construct MAYO's GF(16)
#
# GF(16) = GF(2)[a] / (a^4 + a + 1)
# -------------------------------------------------------

B = PolynomialRing(GF(_sage_const_2 ), names=('z',)); (z,) = B._first_ngens(1)

K = GF(_sage_const_2 **_sage_const_4 , modulus=z**_sage_const_4  + z + _sage_const_1 , names=('a',)); (a,) = K._first_ngens(1)


# Convert MAYO nibble 0..15 into the corresponding
# polynomial-basis GF(16) element.
def F(n):

    n = int(n)

    return (
        ((n >> _sage_const_0 ) & _sage_const_1 )
        + ((n >> _sage_const_1 ) & _sage_const_1 ) * a
        + ((n >> _sage_const_2 ) & _sage_const_1 ) * a**_sage_const_2 
        + ((n >> _sage_const_3 ) & _sage_const_1 ) * a**_sage_const_3 
    )

v = _sage_const_78 
o = _sage_const_8 

names = [
    "x_%d_%d" % (k, j)
    for k in range(v)
    for j in range(o)
]

R = PolynomialRing(
    K,
    names=names,
    order='degrevlex'
)

gens = R.gens()

X = {}

idx = _sage_const_0 

for k in range(v):
    for j in range(o):
        X[(k,j)] = gens[idx]
        idx += _sage_const_1 

# Make names such as x_0_0 available to eval()
env = {
    str(g): g
    for g in gens
}

env["F"] = F

equations = []

with open("mayo_equations.txt", "r") as fp:

    for line in fp:

        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):
            continue

        lhs, rhs = line.split("==")

        lhs = lhs.strip()

        f = eval(lhs, {"__builtins__": {}}, env)

        equations.append(R(f))


print("Loaded equations:", len(equations))
print("Variables:", R.ngens())

from collections import Counter

degrees = Counter(f.degree() for f in equations)

print("Degree distribution:")

for d in sorted(degrees):
    print("degree", d, ":", degrees[d])

    
linear_eqs = [
    f for f in equations
    if f.degree() <= _sage_const_1 
]

quadratic_eqs = [
    f for f in equations
    if f.degree() == _sage_const_2 
]

print("Linear equations:", len(linear_eqs))
print("Quadratic equations:", len(quadratic_eqs))

