

# This file was *autogenerated* from the file solve_linear_sat.sage
from sage.all_cmdline import *   # import sage library

_sage_const_78 = Integer(78); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_0xF = Integer(0xF); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_3 = Integer(3); _sage_const_16 = Integer(16); _sage_const_2 = Integer(2); _sage_const_2808 = Integer(2808)

import re
import subprocess
import sys


v = _sage_const_78 
o = _sage_const_8 

NUM_GF16_VARS = v * o
NUM_BOOL_VARS = NUM_GF16_VARS * _sage_const_4 

INPUT_FILE = "mayo_equations_linear.txt"
CNF_FILE = "mayo_independent_xor.cnf"


print("Input file          :", INPUT_FILE)
print("GF(16) variables    :", NUM_GF16_VARS)
print("Boolean variables   :", NUM_BOOL_VARS)



def gf16_add_int(x, y):

    return (x ** y) & _sage_const_0xF 


def gf16_mul_int(a, b):

    a &= _sage_const_0xF 
    b &= _sage_const_0xF 

    result = _sage_const_0 

    # Polynomial multiplication over GF(2)

    for i in range(_sage_const_4 ):

        if (b >> i) & _sage_const_1 :

            result **= a << i

    # Reduce degrees 6,5,4 modulo:
    #
    #     x^4 + x + 1
    #
    # Therefore:
    #
    #     x^d = x^(d-3) + x^(d-4)
    #
    # for d >= 4.

    for degree in range(_sage_const_6 , _sage_const_3 , -_sage_const_1 ):

        if result & (_sage_const_1  << degree):

            result **= (_sage_const_1  << degree)

            result **= (_sage_const_1  << (degree - _sage_const_3 ))

            result **= (_sage_const_1  << (degree - _sage_const_4 ))

    return result & _sage_const_0xF 


print("\nChecking independent GF(16) implementation...")


for x in range(_sage_const_16 ):

    if gf16_mul_int(x, _sage_const_0 ) != _sage_const_0 :

        raise RuntimeError(
            "GF(16) test failed: x*0 != 0"
        )

    if gf16_mul_int(x, _sage_const_1 ) != x:

        raise RuntimeError(
            "GF(16) test failed: x*1 != x"
        )


for x in range(_sage_const_16 ):

    for y in range(_sage_const_16 ):

        if gf16_mul_int(x, y) != gf16_mul_int(y, x):

            raise RuntimeError(
                "GF(16) multiplication is not commutative"
            )


print("PASS: independent GF(16) sanity checks")


def gf_index(k, j):

    return k * o + j


def sat_var(k, j, bit):

    return _sage_const_4  * gf_index(k, j) + bit + _sage_const_1 


def multiplication_matrix(c):

    matrix = [
        [_sage_const_0  for _ in range(_sage_const_4 )]
        for _ in range(_sage_const_4 )
    ]

    for input_bit in range(_sage_const_4 ):

        basis_element = _sage_const_1  << input_bit

        product = gf16_mul_int(
            c,
            basis_element
        )

        for output_bit in range(_sage_const_4 ):

            matrix[output_bit][input_bit] = (
                (product >> output_bit) & _sage_const_1 
            )

    return matrix


MUL_MATRIX = {

    c: multiplication_matrix(c)

    for c in range(_sage_const_16 )
}



# Variable term:
#
# F(number) * x_k_j

VARIABLE_TERM_RE = re.compile(
    r'^F\(\s*(\d+)\s*\)\s*\*\s*x_(\d+)_(\d+)$'
)


# Constant:
#
# F(number)

CONSTANT_TERM_RE = re.compile(
    r'^F\(\s*(\d+)\s*\)$'
)


def parse_side(side):

    """
    Parse one side of an equation.

    Returns:

        variable_terms:
            dictionary

                (k,j) -> GF(16) nibble coefficient

        constant:
            GF(16) nibble
    """

    variable_terms = {}

    constant = _sage_const_0 


    # Normalize whitespace

    side = side.strip()


    if side == "":
        return variable_terms, constant


    # Equations generated by the C code use '+' between terms.
    #
    # In characteristic 2:
    #
    #       subtraction = addition
    #
    # but the input is expected to contain '+'.

    terms = side.split("+")


    for raw_term in terms:

        term = raw_term.strip()

        if not term:
            continue


        # -----------------------------------------------
        # Variable term:
        #
        # F(c)*x_k_j
        # -----------------------------------------------

        match = VARIABLE_TERM_RE.match(term)

        if match:

            coeff = int(match.group(_sage_const_1 )) & _sage_const_0xF 
            k = int(match.group(_sage_const_2 ))
            j = int(match.group(_sage_const_3 ))


            if not (_sage_const_0  <= k < v):

                raise ValueError(
                    "Invalid oil row index: %d" % k
                )


            if not (_sage_const_0  <= j < o):

                raise ValueError(
                    "Invalid oil column index: %d" % j
                )


            key = (k, j)


            # If the same variable appears multiple times:
            #
            #     c1*x + c2*x
            #
            # combine coefficients using GF(16) addition,
            # which is XOR.

            old = variable_terms.get(
                key,
                _sage_const_0 
            )

            new = gf16_add_int(
                old,
                coeff
            )


            if new == _sage_const_0 :

                variable_terms.pop(
                    key,
                    None
                )

            else:

                variable_terms[key] = new


            continue


        # -----------------------------------------------
        # Constant:
        #
        # F(c)
        # -----------------------------------------------

        match = CONSTANT_TERM_RE.match(term)

        if match:

            value = int(
                match.group(_sage_const_1 )
            ) & _sage_const_0xF 

            constant = gf16_add_int(
                constant,
                value
            )

            continue


        raise ValueError(
            "Could not parse term:\n%s"
            % term
        )


    return variable_terms, constant


# ============================================================
# 7. Parse a complete equation
#
#       lhs == rhs
#
# Move everything to the left:
#
#       lhs + rhs = 0
#
# because characteristic = 2.
# ============================================================

def parse_equation(line):

    if "==" not in line:

        raise ValueError(
            "Equation does not contain ==:\n%s"
            % line
        )


    lhs_text, rhs_text = line.split(
        "==",
        _sage_const_1 
    )


    lhs_vars, lhs_const = parse_side(
        lhs_text
    )

    rhs_vars, rhs_const = parse_side(
        rhs_text
    )


    # Combine both sides:
    #
    # lhs - rhs = 0
    #
    # Over characteristic 2:
    #
    # lhs + rhs = 0

    variables = dict(lhs_vars)


    for key, coeff in rhs_vars.items():

        old = variables.get(
            key,
            _sage_const_0 
        )

        new = gf16_add_int(
            old,
            coeff
        )

        if new == _sage_const_0 :

            variables.pop(
                key,
                None
            )

        else:

            variables[key] = new


    constant = gf16_add_int(
        lhs_const,
        rhs_const
    )


    # Equation is now:
    #
    #       sum(coeff*x) + constant = 0
    #
    # therefore:
    #
    #       sum(coeff*x) = constant
    #
    # since -constant = constant in characteristic 2.

    rhs = constant


    return variables, rhs


parsed_equations = []


with open(INPUT_FILE, "r") as fp:

    for line_no, line in enumerate(
        fp,
        start=_sage_const_1 
    ):

        line = line.strip()


        if not line:

            continue


        if line.startswith("#"):

            continue


        try:

            variables, rhs = parse_equation(
                line
            )

        except Exception as e:

            print(
                "\nERROR parsing line",
                line_no
            )

            print(line)

            print(
                "\nReason:",
                e
            )

            raise


        parsed_equations.append(
            (
                variables,
                rhs
            )
        )


print(
    "\nParsed GF(16) equations:",
    len(parsed_equations)
)


if len(parsed_equations) != _sage_const_2808 :

    print(
        "WARNING: expected 2808 equations"
    )


# ============================================================
# 9. Convert each GF(16) equation into four XOR equations
#
# For:
#
#       sum_j c_j*x_j = rhs
#
# generate:
#
#       bit equation 0
#       bit equation 1
#       bit equation 2
#       bit equation 3
#
# over GF(2).
# ============================================================

xor_equations = []


for eq_index, (variables, rhs) in enumerate(
    parsed_equations
):

    xor_sets = [

        set(),
        set(),
        set(),
        set()

    ]


    for (k, j), coeff in variables.items():

        matrix = MUL_MATRIX[coeff]


        for output_bit in range(_sage_const_4 ):

            for input_bit in range(_sage_const_4 ):

                if matrix[output_bit][input_bit]:

                    variable = sat_var(
                        k,
                        j,
                        input_bit
                    )


                    # XOR insertion:
                    #
                    # x XOR x = 0

                    if variable in xor_sets[output_bit]:

                        xor_sets[output_bit].remove(
                            variable
                        )

                    else:

                        xor_sets[output_bit].add(
                            variable
                        )


    # RHS nibble -> four RHS bits

    for output_bit in range(_sage_const_4 ):

        rhs_bit = (
            rhs >> output_bit
        ) & _sage_const_1 


        xor_equations.append(
            (
                sorted(
                    xor_sets[output_bit]
                ),
                rhs_bit
            )
        )


print(
    "Generated XOR equations:",
    len(xor_equations)
)


expected_xor = (
    len(parsed_equations) * _sage_const_4 
)


print(
    "Expected XOR equations :",
    expected_xor
)


if len(xor_equations) != expected_xor:

    raise RuntimeError(
        "Incorrect XOR equation count"
    )


# ============================================================
# 10. Write CryptoMiniSat XOR-DIMACS
#
# CryptoMiniSat XOR syntax:
#
#       x lit1 lit2 ... 0
#
# represents an XOR constraint with RHS true.
#
# Therefore:
#
#       XOR(vars) = 1
#
# can be written directly.
#
# For:
#
#       XOR(vars) = 0
#
# negate exactly one literal:
#
#       XOR(~x1,x2,...)=1
# ============================================================


with open(CNF_FILE, "w") as fp:

    fp.write(
        "p cnf %d %d\n"
        % (
            NUM_BOOL_VARS,
            len(xor_equations)
        )
    )


    for variables, rhs in xor_equations:


        # -----------------------------------------------
        # Empty XOR
        # -----------------------------------------------

        if len(variables) == _sage_const_0 :

            if rhs == _sage_const_0 :

                # Tautological XOR:
                #
                # x XOR ~x = 1

                fp.write(
                    "x 1 -1 0\n"
                )

            else:

                # Contradiction

                fp.write(
                    "0\n"
                )

            continue


        literals = list(
            variables
        )


        # CryptoMiniSat XOR lines have implicit RHS = 1.
        #
        # Negating one variable toggles parity.

        if rhs == _sage_const_0 :

            literals[_sage_const_0 ] = -literals[_sage_const_0 ]


        fp.write(
            "x "
            + " ".join(
                str(x)
                for x in literals
            )
            + " 0\n"
        )


print(
    "\nWritten:",
    CNF_FILE
)


print("RUNNING CRYPTOMINISAT")


try:

    result = subprocess.run(

        [
            "cryptominisat5",
            CNF_FILE
        ],

        stdout=subprocess.PIPE,

        stderr=subprocess.PIPE,

        universal_newlines=True
    )


except FileNotFoundError:

    print(
        "\ncryptominisat5 not found."
    )

    print(
        "Run manually:"
    )

    print(
        "\ncryptominisat5 %s"
        % CNF_FILE
    )

    sys.exit(_sage_const_1 )


output = result.stdout


print(output)


# 12. Check SAT result

if "s UNSATISFIABLE" in output:

    print("\n========================================")

    print(
        "RESULT: UNSAT"
    )

    print(
        "Independent SAT verification disagrees "
        "with Sage."
    )

    print("========================================")

    sys.exit(_sage_const_1 )


if "s SATISFIABLE" not in output:

    print(
        "ERROR: could not find SAT result."
    )

    sys.exit(_sage_const_1 )


print(
    "\nIndependent CryptoMiniSat result: SAT"
)


# 13. Parse Boolean SAT assignment

assignment = {}


for line in output.splitlines():

    line = line.strip()


    if not line.startswith("v "):

        continue


    for token in line.split()[_sage_const_1 :]:

        literal = int(token)


        if literal == _sage_const_0 :

            continue


        variable = abs(literal)

        assignment[variable] = (
            _sage_const_1  if literal > _sage_const_0  else _sage_const_0 
        )


print(
    "Boolean assignments parsed:",
    len(assignment)
)


O_sat_int = [

    [_sage_const_0  for j in range(o)]

    for k in range(v)

]


for k in range(v):

    for j in range(o):

        nibble = _sage_const_0 


        for bit in range(_sage_const_4 ):

            boolean_variable = sat_var(
                k,
                j,
                bit
            )

            bit_value = assignment.get(
                boolean_variable,
                _sage_const_0 
            )


            nibble |= (
                bit_value << bit
            )


        O_sat_int[k][j] = (
            nibble & _sage_const_0xF 
        )


# ============================================================
# 15. Print independently recovered O
# ============================================================

print("\n========================================")
print("CRYPTOMINISAT RECOVERED O")


for k in range(v):

    print(
        "O[%2d] =" % k,
        " ".join(
            "%x" % O_sat_int[k][j]
            for j in range(o)
        )
    )


print("\n========================================")
print("VERIFYING SAT MODEL AGAINST ORIGINAL")
print("TEXT EQUATIONS")
print("========================================")


verification_ok = True


for eq_index, (variables, rhs) in enumerate(
    parsed_equations
):

    lhs = _sage_const_0 


    for (k, j), coeff in variables.items():

        product = gf16_mul_int(
            coeff,
            O_sat_int[k][j]
        )


        lhs = gf16_add_int(
            lhs,
            product
        )


    if lhs != rhs:

        print(
            "FAIL at equation",
            eq_index
        )

        print(
            "Computed LHS = %x" % lhs
        )

        print(
            "Expected RHS = %x" % rhs
        )


        verification_ok = False

        break


if verification_ok:

    print(
        "PASS: all original GF(16) equations satisfied"
    )

else:

    print(
        "FAIL: SAT model does not satisfy original equations"
    )

    sys.exit(_sage_const_1 )


