

# This file was *autogenerated* from the file solve_quadratic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_78 = Integer(78); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_16 = Integer(16)# ============================================================
# Solve MAYO partial-fault polynomial system
#
# Experimental setup:
#
#   O[0][j] = unknown / legitimately generated
#
#   O[k][j] = 1
#       for k = 1,...,v-1
#       for j = 0,...,o-1
#
# Original variables:
#
#       x_k_j = O[k][j]
#
# After substitution, only:
#
#       q_j = x_0_j
#
# remain unknown.
#
# The input mayo_equations.txt may contain equations such as:
#
#   F(3)*x_0_0*x_4_2 + F(7)*x_2_1 + F(9) == 0
#
# ============================================================


# ------------------------------------------------------------
# 1. Construct MAYO GF(16)
#
# GF(16) = GF(2)[a] / (a^4 + a + 1)
# ------------------------------------------------------------

B = PolynomialRing(GF(_sage_const_2 ), names=('z',)); (z,) = B._first_ngens(1)

K = GF(
    _sage_const_2 **_sage_const_4 ,
    modulus=z**_sage_const_4  + z + _sage_const_1 
, names=('a',)); (a,) = K._first_ngens(1)


# ------------------------------------------------------------
# 2. Convert MAYO nibble 0..15 to GF(16)
# ------------------------------------------------------------

def F(n):

    n = int(n)

    return K(
        ((n >> _sage_const_0 ) & _sage_const_1 )
        + ((n >> _sage_const_1 ) & _sage_const_1 ) * a
        + ((n >> _sage_const_2 ) & _sage_const_1 ) * a**_sage_const_2 
        + ((n >> _sage_const_3 ) & _sage_const_1 ) * a**_sage_const_3 
    )


# ------------------------------------------------------------
# 3. MAYO parameters
# ------------------------------------------------------------

v = _sage_const_78 
o = _sage_const_8 

nvars = v * o

print("v =", v)
print("o =", o)
print("Original variables =", nvars)


# ------------------------------------------------------------
# 4. Construct original polynomial ring
#
# x_k_j = O[k][j]
# ------------------------------------------------------------

names = [
    "x_%d_%d" % (k, j)
    for k in range(v)
    for j in range(o)
]

R = PolynomialRing(
    K,
    names=names,
    order='degrevlex'
)

gens = R.gens()

X = {}

idx = _sage_const_0 

for k in range(v):

    for j in range(o):

        X[(k,j)] = gens[idx]

        idx += _sage_const_1 


# Environment used to parse equation file

env = {
    str(g): g
    for g in gens
}

env["F"] = F


# ------------------------------------------------------------
# 5. Load original equations
# ------------------------------------------------------------

equations = []

with open("mayo_equations_quadratic.txt", "r") as fp:

    for line_no, line in enumerate(fp, start=_sage_const_1 ):

        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):
            continue

        if "==" not in line:

            print(
                "WARNING: skipping malformed line",
                line_no
            )

            continue

        lhs, rhs = line.split("==", _sage_const_1 )

        lhs = lhs.strip()
        rhs = rhs.strip()

        lhs_expr = eval(
            lhs,
            {"__builtins__": {}},
            env
        )

        rhs_expr = eval(
            rhs,
            {"__builtins__": {}},
            env
        )

        f = R(lhs_expr - rhs_expr)

        equations.append(f)


print("\nLoaded equations:", len(equations))
print("Original polynomial variables:", R.ngens())


# ------------------------------------------------------------
# 6. Inspect original degree distribution
# ------------------------------------------------------------

from collections import Counter

degrees_before = Counter(
    f.degree()
    for f in equations
)

print("\nDegree distribution BEFORE substitution:")

for d in sorted(degrees_before):

    print(
        "degree",
        d,
        ":",
        degrees_before[d]
    )


# ============================================================
# 7. Substitute known oil values
#
# Experimental assumption:
#
#       x_k_j = 1
#
# for:
#
#       k = 1,...,77
#
# Only:
#
#       x_0_0,...,x_0_7
#
# remain unknown.
# ============================================================

print("\nSubstituting known oil rows...")

subs = {}

for k in range(_sage_const_1 , v):

    for j in range(o):

        subs[X[(k,j)]] = K(_sage_const_1 )


substituted_equations_R = []

zero_equations = _sage_const_0 

for f in equations:

    g = R(f.subs(subs))

    if g == _sage_const_0 :

        zero_equations += _sage_const_1 

    else:

        substituted_equations_R.append(g)


print(
    "Equations becoming identically zero:",
    zero_equations
)

print(
    "Remaining nonzero equations:",
    len(substituted_equations_R)
)


# ------------------------------------------------------------
# 8. Verify which variables remain
# ------------------------------------------------------------

remaining_vars = set()

for f in substituted_equations_R:

    remaining_vars.update(
        f.variables()
    )


remaining_vars = sorted(
    remaining_vars,
    key=str
)


print("\nVariables actually remaining:")

for var in remaining_vars:

    print(" ", var)

print(
    "\nNumber of remaining variables:",
    len(remaining_vars)
)


# We expect exactly:

expected_remaining = set(
    X[(_sage_const_0 ,j)]
    for j in range(o)
)

unexpected = (
    set(remaining_vars)
    - expected_remaining
)

if unexpected:

    print(
        "\nERROR: variables other than first-row "
        "oil variables remain:"
    )

    for var in unexpected:
        print(var)

    raise RuntimeError(
        "Known-variable substitution incomplete"
    )


# ============================================================
# 9. Create reduced polynomial ring with only 8 variables
#
#       q_0,...,q_7
#
# where:
#
#       q_j = O[0][j]
# ============================================================

q_names = [
    "q_%d" % j
    for j in range(o)
]

S = PolynomialRing(
    K,
    names=q_names,
    order='degrevlex'
)

q = S.gens()


print("\nReduced variables:")

for j in range(o):

    print(
        "q_%d = O[0][%d]" % (j, j)
    )


# ------------------------------------------------------------
# 10. Map R -> S
#
# First-row variables map to q_j.
#
# All other variables map to 1.
# ------------------------------------------------------------

images = []

for k in range(v):

    for j in range(o):

        if k == _sage_const_0 :

            images.append(
                q[j]
            )

        else:

            images.append(
                S(_sage_const_1 )
            )


phi = R.hom(
    images,
    S
)


reduced_equations = []

for f in equations:

    g = phi(f)

    if g != _sage_const_0 :

        reduced_equations.append(g)


print(
    "\nReduced nonzero equations:",
    len(reduced_equations)
)


# ------------------------------------------------------------
# 11. Degree distribution after substitution
# ------------------------------------------------------------

degrees_after = Counter(
    f.degree()
    for f in reduced_equations
)

print(
    "\nDegree distribution AFTER substitution:"
)

for d in sorted(degrees_after):

    print(
        "degree",
        d,
        ":",
        degrees_after[d]
    )


linear_eqs = [
    f
    for f in reduced_equations
    if f.degree() <= _sage_const_1 
]

quadratic_eqs = [
    f
    for f in reduced_equations
    if f.degree() == _sage_const_2 
]


print(
    "\nLinear equations:",
    len(linear_eqs)
)

print(
    "Quadratic equations:",
    len(quadratic_eqs)
)


# ------------------------------------------------------------
# 12. Print a few reduced equations
# ------------------------------------------------------------

print("\nFirst 10 reduced equations:")

for i, f in enumerate(
    reduced_equations[:_sage_const_10 ]
):

    print(
        "[%d] %s == 0"
        % (i, f)
    )


# ============================================================
# 13. Build polynomial ideal
#
# We solve:
#
#       f_1(q) = 0
#       ...
#       f_N(q) = 0
#
# over GF(16).
#
# Since q_j must be GF(16) elements, include:
#
#       q_j^16 - q_j = 0
#
# These are field equations.
# ============================================================

field_equations = [
    qi**_sage_const_16  - qi
    for qi in q
]


all_solver_equations = (
    reduced_equations
    + field_equations
)


print(
    "\nPolynomial equations:",
    len(reduced_equations)
)

print(
    "Field equations:",
    len(field_equations)
)

print(
    "Total ideal generators:",
    len(all_solver_equations)
)


# ------------------------------------------------------------
# 14. Construct ideal
# ------------------------------------------------------------

I = S.ideal(
    all_solver_equations
)


# ============================================================
# 15. Compute Groebner basis
# ============================================================

print("\n========================================")
print("Computing Groebner basis...")
print("========================================")

G = I.groebner_basis()


print(
    "\nGroebner basis size:",
    len(G)
)


print("\nGroebner basis:")

for g in G:

    print(g)


# ============================================================
# 16. SAT / UNSAT check
#
# If Groebner basis contains 1:
#
#       <f1,...,fn> = <1>
#
# and therefore no common solution exists.
# ============================================================

if S(_sage_const_1 ) in G:

    print("\n========================================")
    print("RESULT: UNSAT")
    print("========================================")

    print(
        "The polynomial system has no solution "
        "over GF(16)."
    )

    quit()


print("\n========================================")
print("RESULT: SAT")
print("========================================")

print(
    "The polynomial system has at least "
    "one solution over GF(16)."
)


# ============================================================
# 17. Try to obtain variety / solutions
#
# Only 8 variables remain, so solving the zero-dimensional
# ideal may be practical.
# ============================================================

print("\nAttempting to recover solutions...")


try:

    solutions = I.variety(
        ring=K
    )

except Exception as e:

    print(
        "\nDirect variety() failed:"
    )

    print(e)

    solutions = []


print(
    "\nNumber of solutions found:",
    len(solutions)
)


# ------------------------------------------------------------
# 18. Convert GF(16) element back to MAYO nibble
# ------------------------------------------------------------

def gf16_to_nibble(x):

    x = K(x)

    p = x.polynomial()

    n = _sage_const_0 

    for bit in range(_sage_const_4 ):

        if bit <= p.degree():

            if int(p[bit]) & _sage_const_1 :

                n |= (_sage_const_1  << bit)

    return n


# ------------------------------------------------------------
# 19. Print recovered first oil row
# ------------------------------------------------------------

for sol_no, sol in enumerate(solutions):

    print(
        "\n========================================"
    )

    print(
        "Solution",
        sol_no
    )

    print(
        "========================================"
    )

    recovered = []

    for j in range(o):

        value = sol[q[j]]

        nibble = gf16_to_nibble(
            value
        )

        recovered.append(
            nibble
        )

        print(
            "O[0][%d] = %s  (0x%x)"
            % (
                j,
                value,
                nibble
            )
        )

    print(
        "\nRecovered first oil row (hex):"
    )

    print(
        " ".join(
            "%x" % x
            for x in recovered
        )
    )


# ============================================================
# 20. Verify every recovered solution against ALL original
#     reduced equations
# ============================================================

print(
    "\n========================================"
)

print(
    "Verifying recovered solutions"
)

print(
    "========================================"
)


for sol_no, sol in enumerate(solutions):

    valid = True

    for eq_no, f in enumerate(
        reduced_equations
    ):

        value = f.subs(sol)

        if value != _sage_const_0 :

            print(
                "Solution",
                sol_no,
                "fails equation",
                eq_no
            )

            print(
                "Equation:",
                f
            )

            print(
                "Value:",
                value
            )

            valid = False

            break

    if valid:

        print(
            "Solution",
            sol_no,
            "PASS: satisfies all",
            len(reduced_equations),
            "equations"
        )


