

# This file was *autogenerated* from the file sage/solve_grobner.sage
from sage.all_cmdline import *   # import sage library

_sage_const_78 = Integer(78); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_0xF = Integer(0xF); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_20 = Integer(20); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_200 = Integer(200); _sage_const_400 = Integer(400); _sage_const_600 = Integer(600); _sage_const_800 = Integer(800); _sage_const_1000 = Integer(1000); _sage_const_1200 = Integer(1200); _sage_const_1400 = Integer(1400); _sage_const_1600 = Integer(1600); _sage_const_1800 = Integer(1800); _sage_const_2000 = Integer(2000); _sage_const_2200 = Integer(2200); _sage_const_2400 = Integer(2400); _sage_const_2600 = Integer(2600); _sage_const_70 = Integer(70)
from sage.all import *
import re
import sys
import time


# ============================================================
# PARAMETERS
# ============================================================

v = _sage_const_78 
o = _sage_const_8 

NUM_GF16_VARS = v * o

INPUT_FILE = (
    sys.argv[_sage_const_1 ]
    if len(sys.argv) > _sage_const_1 
    else "sage/mayo_equations_quadratic.txt"
)

BOOLEAN_EQ_FILE = (
    sys.argv[_sage_const_2 ]
    if len(sys.argv) > _sage_const_2 
    else "sage/boolean_anf_equations_quadratic.txt"
)


# ============================================================
# GF(16)
#
# GF(16) = GF(2)[a] / (a^4 + a + 1)
# ============================================================

PR = PolynomialRing(GF(_sage_const_2 ), "z")
z = PR.gen()

F = GF(
    _sage_const_2 **_sage_const_4 ,
    name="a",
    modulus=z**_sage_const_4  + z + _sage_const_1 
)

a = F.gen()


# ============================================================
# GF(16) POLYNOMIAL RING
#
# Unknowns are Oil matrix entries:
#
#   x_0_0 ... x_77_7
#
# ============================================================

gf_names = [
    "x_%d_%d" % (k, j)
    for k in range(v)
    for j in range(o)
]

R = PolynomialRing(
    F,
    names=gf_names,
    order="degrevlex"
)

Rvars = list(R.gens())


gf_var_map = {}

for k in range(v):
    for j in range(o):
        gf_var_map[(k, j)] = (
            Rvars[k * o + j]
        )


print("========================================")
print("GF(16) PARTIAL-FAULT EQUATION CONVERTER")
print("========================================")

print("Input file       :", INPUT_FILE)
print("Output file      :", BOOLEAN_EQ_FILE)
print("GF(16) variables :", NUM_GF16_VARS)
print("GF(16) field     :", F)
print("Modulus          :", F.modulus())


# ============================================================
# INTEGER/NIBBLE -> GF(16)
# ============================================================

def int_to_gf16(c):

    c = int(c) & _sage_const_0xF 

    value = F(_sage_const_0 )

    for bit in range(_sage_const_4 ):

        if (c >> bit) & _sage_const_1 :
            value += a**bit

    return value


# ============================================================
# PARSING GF(16) EQUATIONS
#
# Supports:
#
#   F(3)*x_0_0
#
#   F(3)*x_0_0*x_1_2
#
#   F(3)*x_0_0^2
#
#   x_0_0*x_1_2
#
#   F(7)
#
#   7
#
# Equations:
#
#   lhs == rhs
#
# or
#
#   lhs = rhs
#
# ============================================================

VAR_RE = re.compile(
    r"^x_(\d+)_(\d+)(?:\^(\d+))?$"
)

COEFF_RE = re.compile(
    r"^F\(\s*(\d+)\s*\)$"
)

EQ_PREFIX_RE = re.compile(
    r"^\s*Eq\s+\d+\s*:\s*",
    re.IGNORECASE
)


def parse_variable_factor(text):

    m = VAR_RE.fullmatch(text.strip())

    if not m:
        raise ValueError(
            "Invalid variable factor: %r"
            % text
        )

    k = int(m.group(_sage_const_1 ))
    j = int(m.group(_sage_const_2 ))

    exponent = (
        int(m.group(_sage_const_3 ))
        if m.group(_sage_const_3 )
        else _sage_const_1 
    )

    if not (_sage_const_0  <= k < v):
        raise ValueError(
            "Invalid row index: %d"
            % k
        )

    if not (_sage_const_0  <= j < o):
        raise ValueError(
            "Invalid column index: %d"
            % j
        )

    if exponent < _sage_const_1 :
        raise ValueError(
            "Invalid exponent: %d"
            % exponent
        )

    return (
        gf_var_map[(k, j)],
        exponent
    )


def parse_term(term):
    """
    Examples:

        F(5)*x_0_0

        F(5)*x_0_0*x_3_2

        F(5)*x_0_0^2

        x_0_0*x_3_2

        F(5)

        5

    Returns a Sage polynomial in R.
    """

    term = term.strip()

    if not term:
        return R(_sage_const_0 )

    factors = [
        x.strip()
        for x in term.split("*")
        if x.strip()
    ]

    coeff = F(_sage_const_1 )

    variable_factors = []

    for factor in factors:

        # ----------------------------------------
        # F(c)
        # ----------------------------------------

        m = COEFF_RE.fullmatch(factor)

        if m:

            coeff *= int_to_gf16(
                int(m.group(_sage_const_1 ))
            )

            continue

        # ----------------------------------------
        # Bare integer
        # ----------------------------------------

        if factor.isdigit():

            coeff *= int_to_gf16(
                int(factor)
            )

            continue

        # ----------------------------------------
        # Variable
        # ----------------------------------------

        variable, exponent = (
            parse_variable_factor(factor)
        )

        variable_factors.append(
            (variable, exponent)
        )

    result = R(coeff)

    for variable, exponent in variable_factors:

        result *= variable**exponent

    return result


def parse_side(side):

    side = side.strip()

    if not side:
        return R(_sage_const_0 )

    result = R(_sage_const_0 )

    for raw_term in side.split("+"):

        term = raw_term.strip()

        if not term:
            continue

        result += parse_term(term)

    return result


def parse_equation(line):

    line = line.strip()

    line = EQ_PREFIX_RE.sub(
        "",
        line,
        count=_sage_const_1 
    )

    if "==" in line:

        lhs_text, rhs_text = (
            line.split("==", _sage_const_1 )
        )

    elif "=" in line:

        lhs_text, rhs_text = (
            line.split("=", _sage_const_1 )
        )

    else:

        raise ValueError(
            "Equation has no '=' or '==': %s"
            % line
        )

    lhs = parse_side(lhs_text)

    rhs = parse_side(rhs_text)

    # characteristic 2:
    #
    # lhs = rhs
    #
    # becomes
    #
    # lhs + rhs = 0

    return lhs + rhs


# ============================================================
# READ GF(16) SYSTEM
# ============================================================

gf16_system = []


with open(INPUT_FILE, "r") as fp:

    for line_no, line in enumerate(
        fp,
        start=_sage_const_1 
    ):

        line = line.strip()

        if (
            not line
            or line.startswith("#")
        ):
            continue

        try:

            f = parse_equation(line)

        except Exception as e:

            print()
            print(
                "ERROR parsing line",
                line_no
            )

            print(line)

            print(
                "Reason:",
                e
            )

            raise

        gf16_system.append(f)


if not gf16_system:

    raise RuntimeError(
        "No GF(16) equations parsed"
    )


gf_degrees = [
    f.total_degree()
    for f in gf16_system
]


print()
print("Parsed GF(16) equations :", len(gf16_system))
print("Maximum GF(16) degree   :", max(gf_degrees))

print(
    "Linear equations        :",
    sum(d <= _sage_const_1  for d in gf_degrees)
)

print(
    "Quadratic equations     :",
    sum(d == _sage_const_2  for d in gf_degrees)
)

print(
    "Degree > 2 equations    :",
    sum(d > _sage_const_2  for d in gf_degrees)
)


# ============================================================
# GF(16) -> GF(2) BIT BLAST
# ============================================================

def gf2m_system_to_gf2(system):

    R_ext = system[_sage_const_0 ].parent()

    F_ext = R_ext.base_ring()

    m = F_ext.degree()

    vars_ext = list(
        R_ext.gens()
    )

    n = len(vars_ext)

    modulus = F_ext.modulus()

    modulus_coeffs = list(
        modulus.list()
    )

    # ========================================================
    # BOOLEAN VARIABLES
    #
    # x_i_j ->
    #
    #   x_i_j_b0
    #   x_i_j_b1
    #   x_i_j_b2
    #   x_i_j_b3
    # ========================================================

    bool_names = []

    for var in vars_ext:

        for bit in range(m):

            bool_names.append(
                "%s_b%d"
                %
                (
                    str(var),
                    bit
                )
            )

    B = BooleanPolynomialRing(
        n * m,
        names=bool_names
    )

    Bvars = list(
        B.gens()
    )

    var_bits = {}

    index = _sage_const_0 

    for var in vars_ext:

        var_bits[var] = list(
            Bvars[
                index:
                index + m
            ]
        )

        index += m


    # ========================================================
    # FIELD ELEMENT -> BASIS BITS
    # ========================================================

    def field_element_to_bits(c):

        c = F_ext(c)

        poly = c.polynomial()

        coeffs = list(
            poly.list()
        )

        coeffs += (
            [_sage_const_0 ]
            *
            (m - len(coeffs))
        )

        return [

            B(
                int(coeffs[i])
            )

            for i in range(m)

        ]


    # ========================================================
    # SYMBOLIC GF(16) MULTIPLICATION
    #
    # This is what allows quadratic terms.
    #
    # If:
    #
    #   X = x0 + x1*a + x2*a² + x3*a³
    #
    #   Y = y0 + y1*a + y2*a² + y3*a³
    #
    # then field_mult() creates Boolean products:
    #
    #   xi*yj
    #
    # and reduces powers of a modulo:
    #
    #   a^4 + a + 1
    # ========================================================

    def field_mult(u_bits, v_bits):

        tmp = [

            B(_sage_const_0 )

            for _ in range(
                _sage_const_2  * m - _sage_const_1 
            )

        ]

        # polynomial multiplication

        for i in range(m):

            for j in range(m):

                tmp[i + j] += (
                    u_bits[i]
                    *
                    v_bits[j]
                )

        # modular reduction

        for degree in range(
            _sage_const_2  * m - _sage_const_2 ,
            m - _sage_const_1 ,
            -_sage_const_1 
        ):

            high = tmp[degree]

            if high == B(_sage_const_0 ):
                continue

            for i in range(m):

                if (
                    int(
                        modulus_coeffs[i]
                    )
                    & _sage_const_1 
                ):

                    tmp[
                        degree - m + i
                    ] += high

            tmp[degree] = B(_sage_const_0 )

        return tmp[:m]


    def multiply_by_variable_power(
        term_bits,
        variable,
        exponent
    ):

        result = list(
            term_bits
        )

        bits = var_bits[
            variable
        ]

        for _ in range(exponent):

            result = field_mult(
                result,
                bits
            )

        return result


    # ========================================================
    # CONVERT SYSTEM
    # ========================================================

    boolean_eqs = []

    print()
    print("Bit-blasting GF(16) equations...")

    for eq_index, f in enumerate(system):

        result = [

            B(_sage_const_0 )

            for _ in range(m)

        ]

        for mon in f.monomials():

            coeff = F_ext(
                f.monomial_coefficient(
                    mon
                )
            )

            term_bits = (
                field_element_to_bits(
                    coeff
                )
            )

            exponent_tuple = tuple(
                mon.exponents()[_sage_const_0 ]
            )

            for (
                var_index,
                exponent
            ) in enumerate(
                exponent_tuple
            ):

                exponent = int(exponent)

                if exponent == _sage_const_0 :
                    continue

                variable = (
                    vars_ext[var_index]
                )

                term_bits = (
                    multiply_by_variable_power(
                        term_bits,
                        variable,
                        exponent
                    )
                )

            for bit in range(m):

                result[bit] += (
                    term_bits[bit]
                )

        # One GF(16) equation ->
        # four GF(2) equations.

        for bit in range(m):

            boolean_eqs.append(
                B(result[bit])
            )

    return (
        B,
        var_bits,
        boolean_eqs
    )
# ============================================================
# GROBNER BASIS SOLVER
# ============================================================

print()
print("========================================")
print("Computing Grobner basis over GF(16)")
print("========================================")

t0 = time.time()
# ============================================================
# INCREMENTAL GROBNER BASIS
# ============================================================

print()
print("========================================")
print("Incremental Groebner Basis Test")
print("========================================")

# Number of equations to try
sizes = [
    _sage_const_10 ,
    _sage_const_20 ,
    _sage_const_50 ,
    _sage_const_100 ,
    _sage_const_200 ,
    _sage_const_400 ,
    _sage_const_600 ,
    _sage_const_800 ,
    _sage_const_1000 ,
    _sage_const_1200 ,
    _sage_const_1400 ,
    _sage_const_1600 ,
    _sage_const_1800 ,
    _sage_const_2000 ,
    _sage_const_2200 ,
    _sage_const_2400 ,
    _sage_const_2600 ,
    len(gf16_system)
]

for N in sizes:

    if N > len(gf16_system):
        continue

    print()
    print("=" * _sage_const_70 )
    print("Testing first %d equations" % N)
    print("=" * _sage_const_70 )

    try:

        t0 = time.time()

        I = R.ideal(gf16_system[:N])

        print("Ideal created in %.2f s" %
              (time.time() - t0))

        sys.stdout.flush()

        t1 = time.time()

        G = I.groebner_basis()

        gb_time = time.time() - t1

        print("SUCCESS")
        print("Groebner time : %.2f s" % gb_time)
        print("Basis size    :", len(G))

        # Print degree statistics
        degrees = [g.total_degree() for g in G]

        print("Maximum degree :", max(degrees))
        print("Average degree : %.2f" %
              (sum(degrees)/len(degrees)))

        if R(_sage_const_1 ) in G:
            print("Ideal contains 1 (UNSAT)")
        else:
            print("Ideal does not contain 1")

    except KeyboardInterrupt:
        raise

    except Exception as e:

        print()
        print("FAILED at %d equations" % N)
        print(type(e).__name__)
        print(e)

        break

